// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/optionalFields.proto

package se.tink.protobuf.optional;

public final class TinkProtoOptionalFields {
  private TinkProtoOptionalFields() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OptionalObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:se.tink.OptionalObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
     * @return Whether the complexValue field is set.
     */
    boolean hasComplexValue();
    /**
     * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
     * @return The complexValue.
     */
    se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue getComplexValue();
    /**
     * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
     */
    se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder getComplexValueOrBuilder();
  }
  /**
   * Protobuf type {@code se.tink.OptionalObject}
   */
  public static final class OptionalObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:se.tink.OptionalObject)
      OptionalObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OptionalObject.newBuilder() to construct.
    private OptionalObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalObject() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OptionalObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.class, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPLEXVALUE_FIELD_NUMBER = 3;
    private se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue complexValue_;
    /**
     * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
     * @return Whether the complexValue field is set.
     */
    @java.lang.Override
    public boolean hasComplexValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
     * @return The complexValue.
     */
    @java.lang.Override
    public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue getComplexValue() {
      return complexValue_ == null ? se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance() : complexValue_;
    }
    /**
     * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
     */
    @java.lang.Override
    public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder getComplexValueOrBuilder() {
      return complexValue_ == null ? se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance() : complexValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getComplexValue());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getComplexValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject)) {
        return super.equals(obj);
      }
      se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject other = (se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasComplexValue() != other.hasComplexValue()) return false;
      if (hasComplexValue()) {
        if (!getComplexValue()
            .equals(other.getComplexValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasComplexValue()) {
        hash = (37 * hash) + COMPLEXVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getComplexValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code se.tink.OptionalObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:se.tink.OptionalObject)
        se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.class, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.Builder.class);
      }

      // Construct using se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getComplexValueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        if (complexValueBuilder_ == null) {
          complexValue_ = null;
        } else {
          complexValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalObject_descriptor;
      }

      @java.lang.Override
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject getDefaultInstanceForType() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.getDefaultInstance();
      }

      @java.lang.Override
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject build() {
        se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject buildPartial() {
        se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject result = new se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (complexValueBuilder_ == null) {
            result.complexValue_ = complexValue_;
          } else {
            result.complexValue_ = complexValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject) {
          return mergeFrom((se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject other) {
        if (other == se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasComplexValue()) {
          mergeComplexValue(other.getComplexValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getComplexValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue complexValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder> complexValueBuilder_;
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       * @return Whether the complexValue field is set.
       */
      public boolean hasComplexValue() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       * @return The complexValue.
       */
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue getComplexValue() {
        if (complexValueBuilder_ == null) {
          return complexValue_ == null ? se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance() : complexValue_;
        } else {
          return complexValueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      public Builder setComplexValue(se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue value) {
        if (complexValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          complexValue_ = value;
          onChanged();
        } else {
          complexValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      public Builder setComplexValue(
          se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder builderForValue) {
        if (complexValueBuilder_ == null) {
          complexValue_ = builderForValue.build();
          onChanged();
        } else {
          complexValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      public Builder mergeComplexValue(se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue value) {
        if (complexValueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              complexValue_ != null &&
              complexValue_ != se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance()) {
            complexValue_ =
              se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.newBuilder(complexValue_).mergeFrom(value).buildPartial();
          } else {
            complexValue_ = value;
          }
          onChanged();
        } else {
          complexValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      public Builder clearComplexValue() {
        if (complexValueBuilder_ == null) {
          complexValue_ = null;
          onChanged();
        } else {
          complexValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder getComplexValueBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getComplexValueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder getComplexValueOrBuilder() {
        if (complexValueBuilder_ != null) {
          return complexValueBuilder_.getMessageOrBuilder();
        } else {
          return complexValue_ == null ?
              se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance() : complexValue_;
        }
      }
      /**
       * <code>optional .se.tink.OptionalComplexValue complexValue = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder> 
          getComplexValueFieldBuilder() {
        if (complexValueBuilder_ == null) {
          complexValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder>(
                  getComplexValue(),
                  getParentForChildren(),
                  isClean());
          complexValue_ = null;
        }
        return complexValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:se.tink.OptionalObject)
    }

    // @@protoc_insertion_point(class_scope:se.tink.OptionalObject)
    private static final se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject();
    }

    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalObject>
        PARSER = new com.google.protobuf.AbstractParser<OptionalObject>() {
      @java.lang.Override
      public OptionalObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OptionalObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OptionalComplexValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:se.tink.OptionalComplexValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code se.tink.OptionalComplexValue}
   */
  public static final class OptionalComplexValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:se.tink.OptionalComplexValue)
      OptionalComplexValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OptionalComplexValue.newBuilder() to construct.
    private OptionalComplexValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalComplexValue() {
      name_ = "";
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OptionalComplexValue();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalComplexValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalComplexValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.class, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue)) {
        return super.equals(obj);
      }
      se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue other = (se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code se.tink.OptionalComplexValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:se.tink.OptionalComplexValue)
        se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalComplexValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalComplexValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.class, se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.Builder.class);
      }

      // Construct using se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        type_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.internal_static_se_tink_OptionalComplexValue_descriptor;
      }

      @java.lang.Override
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue getDefaultInstanceForType() {
        return se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance();
      }

      @java.lang.Override
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue build() {
        se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue buildPartial() {
        se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue result = new se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue(this);
        result.name_ = name_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue) {
          return mergeFrom((se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue other) {
        if (other == se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                type_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:se.tink.OptionalComplexValue)
    }

    // @@protoc_insertion_point(class_scope:se.tink.OptionalComplexValue)
    private static final se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue();
    }

    public static se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalComplexValue>
        PARSER = new com.google.protobuf.AbstractParser<OptionalComplexValue>() {
      @java.lang.Override
      public OptionalComplexValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OptionalComplexValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalComplexValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public se.tink.protobuf.optional.TinkProtoOptionalFields.OptionalComplexValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_se_tink_OptionalObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_se_tink_OptionalObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_se_tink_OptionalComplexValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_se_tink_OptionalComplexValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/resources/optionalFields.prot" +
      "o\022\007se.tink\"u\n\016OptionalObject\022\n\n\002id\030\001 \001(\003" +
      "\022\014\n\004name\030\002 \001(\t\0228\n\014complexValue\030\003 \001(\0132\035.s" +
      "e.tink.OptionalComplexValueH\000\210\001\001B\017\n\r_com" +
      "plexValue\"2\n\024OptionalComplexValue\022\014\n\004nam" +
      "e\030\001 \001(\t\022\014\n\004type\030\002 \001(\tB4\n\031se.tink.protobu" +
      "f.optionalB\027TinkProtoOptionalFieldsb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_se_tink_OptionalObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_se_tink_OptionalObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_se_tink_OptionalObject_descriptor,
        new java.lang.String[] { "Id", "Name", "ComplexValue", "ComplexValue", });
    internal_static_se_tink_OptionalComplexValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_se_tink_OptionalComplexValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_se_tink_OptionalComplexValue_descriptor,
        new java.lang.String[] { "Name", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
