// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/customNullableFields.proto

package se.tink.protobuf.custom;

public interface CustomNullableObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.tink.CustomNullableObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
   * @return Whether the complexValue field is set.
   */
  boolean hasComplexValue();
  /**
   * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
   * @return The complexValue.
   */
  se.tink.protobuf.custom.NullableComplexValue getComplexValue();
  /**
   * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
   */
  se.tink.protobuf.custom.NullableComplexValueOrBuilder getComplexValueOrBuilder();
}
