// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/customNullableFields.proto

package se.tink.protobuf.custom;

/**
 * Protobuf type {@code se.tink.CustomNullableObject}
 */
public final class CustomNullableObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:se.tink.CustomNullableObject)
    CustomNullableObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomNullableObject.newBuilder() to construct.
  private CustomNullableObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomNullableObject() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CustomNullableObject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_CustomNullableObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_CustomNullableObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            se.tink.protobuf.custom.CustomNullableObject.class, se.tink.protobuf.custom.CustomNullableObject.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPLEXVALUE_FIELD_NUMBER = 3;
  private se.tink.protobuf.custom.NullableComplexValue complexValue_;
  /**
   * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
   * @return Whether the complexValue field is set.
   */
  @java.lang.Override
  public boolean hasComplexValue() {
    return complexValue_ != null;
  }
  /**
   * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
   * @return The complexValue.
   */
  @java.lang.Override
  public se.tink.protobuf.custom.NullableComplexValue getComplexValue() {
    return complexValue_ == null ? se.tink.protobuf.custom.NullableComplexValue.getDefaultInstance() : complexValue_;
  }
  /**
   * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
   */
  @java.lang.Override
  public se.tink.protobuf.custom.NullableComplexValueOrBuilder getComplexValueOrBuilder() {
    return getComplexValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (complexValue_ != null) {
      output.writeMessage(3, getComplexValue());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (complexValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getComplexValue());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof se.tink.protobuf.custom.CustomNullableObject)) {
      return super.equals(obj);
    }
    se.tink.protobuf.custom.CustomNullableObject other = (se.tink.protobuf.custom.CustomNullableObject) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasComplexValue() != other.hasComplexValue()) return false;
    if (hasComplexValue()) {
      if (!getComplexValue()
          .equals(other.getComplexValue())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasComplexValue()) {
      hash = (37 * hash) + COMPLEXVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getComplexValue().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.tink.protobuf.custom.CustomNullableObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(se.tink.protobuf.custom.CustomNullableObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code se.tink.CustomNullableObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:se.tink.CustomNullableObject)
      se.tink.protobuf.custom.CustomNullableObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_CustomNullableObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_CustomNullableObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.tink.protobuf.custom.CustomNullableObject.class, se.tink.protobuf.custom.CustomNullableObject.Builder.class);
    }

    // Construct using se.tink.protobuf.custom.CustomNullableObject.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      if (complexValueBuilder_ == null) {
        complexValue_ = null;
      } else {
        complexValue_ = null;
        complexValueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_CustomNullableObject_descriptor;
    }

    @java.lang.Override
    public se.tink.protobuf.custom.CustomNullableObject getDefaultInstanceForType() {
      return se.tink.protobuf.custom.CustomNullableObject.getDefaultInstance();
    }

    @java.lang.Override
    public se.tink.protobuf.custom.CustomNullableObject build() {
      se.tink.protobuf.custom.CustomNullableObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public se.tink.protobuf.custom.CustomNullableObject buildPartial() {
      se.tink.protobuf.custom.CustomNullableObject result = new se.tink.protobuf.custom.CustomNullableObject(this);
      result.id_ = id_;
      result.name_ = name_;
      if (complexValueBuilder_ == null) {
        result.complexValue_ = complexValue_;
      } else {
        result.complexValue_ = complexValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof se.tink.protobuf.custom.CustomNullableObject) {
        return mergeFrom((se.tink.protobuf.custom.CustomNullableObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(se.tink.protobuf.custom.CustomNullableObject other) {
      if (other == se.tink.protobuf.custom.CustomNullableObject.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasComplexValue()) {
        mergeComplexValue(other.getComplexValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();

              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getComplexValueFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private se.tink.protobuf.custom.NullableComplexValue complexValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        se.tink.protobuf.custom.NullableComplexValue, se.tink.protobuf.custom.NullableComplexValue.Builder, se.tink.protobuf.custom.NullableComplexValueOrBuilder> complexValueBuilder_;
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     * @return Whether the complexValue field is set.
     */
    public boolean hasComplexValue() {
      return complexValueBuilder_ != null || complexValue_ != null;
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     * @return The complexValue.
     */
    public se.tink.protobuf.custom.NullableComplexValue getComplexValue() {
      if (complexValueBuilder_ == null) {
        return complexValue_ == null ? se.tink.protobuf.custom.NullableComplexValue.getDefaultInstance() : complexValue_;
      } else {
        return complexValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    public Builder setComplexValue(se.tink.protobuf.custom.NullableComplexValue value) {
      if (complexValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        complexValue_ = value;
        onChanged();
      } else {
        complexValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    public Builder setComplexValue(
        se.tink.protobuf.custom.NullableComplexValue.Builder builderForValue) {
      if (complexValueBuilder_ == null) {
        complexValue_ = builderForValue.build();
        onChanged();
      } else {
        complexValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    public Builder mergeComplexValue(se.tink.protobuf.custom.NullableComplexValue value) {
      if (complexValueBuilder_ == null) {
        if (complexValue_ != null) {
          complexValue_ =
            se.tink.protobuf.custom.NullableComplexValue.newBuilder(complexValue_).mergeFrom(value).buildPartial();
        } else {
          complexValue_ = value;
        }
        onChanged();
      } else {
        complexValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    public Builder clearComplexValue() {
      if (complexValueBuilder_ == null) {
        complexValue_ = null;
        onChanged();
      } else {
        complexValue_ = null;
        complexValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    public se.tink.protobuf.custom.NullableComplexValue.Builder getComplexValueBuilder() {
      
      onChanged();
      return getComplexValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    public se.tink.protobuf.custom.NullableComplexValueOrBuilder getComplexValueOrBuilder() {
      if (complexValueBuilder_ != null) {
        return complexValueBuilder_.getMessageOrBuilder();
      } else {
        return complexValue_ == null ?
            se.tink.protobuf.custom.NullableComplexValue.getDefaultInstance() : complexValue_;
      }
    }
    /**
     * <code>.se.tink.NullableComplexValue complexValue = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        se.tink.protobuf.custom.NullableComplexValue, se.tink.protobuf.custom.NullableComplexValue.Builder, se.tink.protobuf.custom.NullableComplexValueOrBuilder> 
        getComplexValueFieldBuilder() {
      if (complexValueBuilder_ == null) {
        complexValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            se.tink.protobuf.custom.NullableComplexValue, se.tink.protobuf.custom.NullableComplexValue.Builder, se.tink.protobuf.custom.NullableComplexValueOrBuilder>(
                getComplexValue(),
                getParentForChildren(),
                isClean());
        complexValue_ = null;
      }
      return complexValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:se.tink.CustomNullableObject)
  }

  // @@protoc_insertion_point(class_scope:se.tink.CustomNullableObject)
  private static final se.tink.protobuf.custom.CustomNullableObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new se.tink.protobuf.custom.CustomNullableObject();
  }

  public static se.tink.protobuf.custom.CustomNullableObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomNullableObject>
      PARSER = new com.google.protobuf.AbstractParser<CustomNullableObject>() {
    @java.lang.Override
    public CustomNullableObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CustomNullableObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomNullableObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public se.tink.protobuf.custom.CustomNullableObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

