// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/customNullableFields.proto

package se.tink.protobuf.custom;

public interface NullableStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.tink.NullableString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return Whether the null field is set.
   */
  boolean hasNull();
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The enum numeric value on the wire for null.
   */
  int getNullValue();
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The null.
   */
  com.google.protobuf.NullValue getNull();

  /**
   * <code>string data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  public se.tink.protobuf.custom.NullableString.KindCase getKindCase();
}
