// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/customNullableFields.proto

package se.tink.protobuf.custom;

public interface NullableComplexValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.tink.NullableComplexValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return Whether the null field is set.
   */
  boolean hasNull();
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The enum numeric value on the wire for null.
   */
  int getNullValue();
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The null.
   */
  com.google.protobuf.NullValue getNull();

  /**
   * <code>.se.tink.ComplexValue complexValue = 2;</code>
   * @return Whether the complexValue field is set.
   */
  boolean hasComplexValue();
  /**
   * <code>.se.tink.ComplexValue complexValue = 2;</code>
   * @return The complexValue.
   */
  se.tink.protobuf.custom.ComplexValue getComplexValue();
  /**
   * <code>.se.tink.ComplexValue complexValue = 2;</code>
   */
  se.tink.protobuf.custom.ComplexValueOrBuilder getComplexValueOrBuilder();

  public se.tink.protobuf.custom.NullableComplexValue.KindCase getKindCase();
}
