// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/customNullableFields.proto

package se.tink.protobuf.custom;

/**
 * Protobuf type {@code se.tink.NullableComplexValue}
 */
public final class NullableComplexValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:se.tink.NullableComplexValue)
    NullableComplexValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NullableComplexValue.newBuilder() to construct.
  private NullableComplexValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NullableComplexValue() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NullableComplexValue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_NullableComplexValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_NullableComplexValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            se.tink.protobuf.custom.NullableComplexValue.class, se.tink.protobuf.custom.NullableComplexValue.Builder.class);
  }

  private int kindCase_ = 0;
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NULL(1),
    COMPLEXVALUE(2),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return NULL;
        case 2: return COMPLEXVALUE;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int NULL_FIELD_NUMBER = 1;
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return Whether the null field is set.
   */
  public boolean hasNull() {
    return kindCase_ == 1;
  }
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The enum numeric value on the wire for null.
   */
  public int getNullValue() {
    if (kindCase_ == 1) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The null.
   */
  public com.google.protobuf.NullValue getNull() {
    if (kindCase_ == 1) {
      @SuppressWarnings("deprecation")
      com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
          (java.lang.Integer) kind_);
      return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
    }
    return com.google.protobuf.NullValue.NULL_VALUE;
  }

  public static final int COMPLEXVALUE_FIELD_NUMBER = 2;
  /**
   * <code>.se.tink.ComplexValue complexValue = 2;</code>
   * @return Whether the complexValue field is set.
   */
  @java.lang.Override
  public boolean hasComplexValue() {
    return kindCase_ == 2;
  }
  /**
   * <code>.se.tink.ComplexValue complexValue = 2;</code>
   * @return The complexValue.
   */
  @java.lang.Override
  public se.tink.protobuf.custom.ComplexValue getComplexValue() {
    if (kindCase_ == 2) {
       return (se.tink.protobuf.custom.ComplexValue) kind_;
    }
    return se.tink.protobuf.custom.ComplexValue.getDefaultInstance();
  }
  /**
   * <code>.se.tink.ComplexValue complexValue = 2;</code>
   */
  @java.lang.Override
  public se.tink.protobuf.custom.ComplexValueOrBuilder getComplexValueOrBuilder() {
    if (kindCase_ == 2) {
       return (se.tink.protobuf.custom.ComplexValue) kind_;
    }
    return se.tink.protobuf.custom.ComplexValue.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeEnum(1, ((java.lang.Integer) kind_));
    }
    if (kindCase_ == 2) {
      output.writeMessage(2, (se.tink.protobuf.custom.ComplexValue) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ((java.lang.Integer) kind_));
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (se.tink.protobuf.custom.ComplexValue) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof se.tink.protobuf.custom.NullableComplexValue)) {
      return super.equals(obj);
    }
    se.tink.protobuf.custom.NullableComplexValue other = (se.tink.protobuf.custom.NullableComplexValue) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (getNullValue()
            != other.getNullValue()) return false;
        break;
      case 2:
        if (!getComplexValue()
            .equals(other.getComplexValue())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + NULL_FIELD_NUMBER;
        hash = (53 * hash) + getNullValue();
        break;
      case 2:
        hash = (37 * hash) + COMPLEXVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getComplexValue().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.tink.protobuf.custom.NullableComplexValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(se.tink.protobuf.custom.NullableComplexValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code se.tink.NullableComplexValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:se.tink.NullableComplexValue)
      se.tink.protobuf.custom.NullableComplexValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_NullableComplexValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_NullableComplexValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.tink.protobuf.custom.NullableComplexValue.class, se.tink.protobuf.custom.NullableComplexValue.Builder.class);
    }

    // Construct using se.tink.protobuf.custom.NullableComplexValue.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (complexValueBuilder_ != null) {
        complexValueBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return se.tink.protobuf.custom.TinkProtoCustomNullable.internal_static_se_tink_NullableComplexValue_descriptor;
    }

    @java.lang.Override
    public se.tink.protobuf.custom.NullableComplexValue getDefaultInstanceForType() {
      return se.tink.protobuf.custom.NullableComplexValue.getDefaultInstance();
    }

    @java.lang.Override
    public se.tink.protobuf.custom.NullableComplexValue build() {
      se.tink.protobuf.custom.NullableComplexValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public se.tink.protobuf.custom.NullableComplexValue buildPartial() {
      se.tink.protobuf.custom.NullableComplexValue result = new se.tink.protobuf.custom.NullableComplexValue(this);
      if (kindCase_ == 1) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 2) {
        if (complexValueBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = complexValueBuilder_.build();
        }
      }
      result.kindCase_ = kindCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof se.tink.protobuf.custom.NullableComplexValue) {
        return mergeFrom((se.tink.protobuf.custom.NullableComplexValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(se.tink.protobuf.custom.NullableComplexValue other) {
      if (other == se.tink.protobuf.custom.NullableComplexValue.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case NULL: {
          setNullValue(other.getNullValue());
          break;
        }
        case COMPLEXVALUE: {
          mergeComplexValue(other.getComplexValue());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              kindCase_ = 1;
              kind_ = rawValue;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getComplexValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return Whether the null field is set.
     */
    @java.lang.Override
    public boolean hasNull() {
      return kindCase_ == 1;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The enum numeric value on the wire for null.
     */
    @java.lang.Override
    public int getNullValue() {
      if (kindCase_ == 1) {
        return ((java.lang.Integer) kind_).intValue();
      }
      return 0;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @param value The enum numeric value on the wire for null to set.
     * @return This builder for chaining.
     */
    public Builder setNullValue(int value) {
      kindCase_ = 1;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return The null.
     */
    @java.lang.Override
    public com.google.protobuf.NullValue getNull() {
      if (kindCase_ == 1) {
        @SuppressWarnings("deprecation")
        com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
            (java.lang.Integer) kind_);
        return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
      }
      return com.google.protobuf.NullValue.NULL_VALUE;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @param value The null to set.
     * @return This builder for chaining.
     */
    public Builder setNull(com.google.protobuf.NullValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      kindCase_ = 1;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.NullValue null = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNull() {
      if (kindCase_ == 1) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        se.tink.protobuf.custom.ComplexValue, se.tink.protobuf.custom.ComplexValue.Builder, se.tink.protobuf.custom.ComplexValueOrBuilder> complexValueBuilder_;
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     * @return Whether the complexValue field is set.
     */
    @java.lang.Override
    public boolean hasComplexValue() {
      return kindCase_ == 2;
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     * @return The complexValue.
     */
    @java.lang.Override
    public se.tink.protobuf.custom.ComplexValue getComplexValue() {
      if (complexValueBuilder_ == null) {
        if (kindCase_ == 2) {
          return (se.tink.protobuf.custom.ComplexValue) kind_;
        }
        return se.tink.protobuf.custom.ComplexValue.getDefaultInstance();
      } else {
        if (kindCase_ == 2) {
          return complexValueBuilder_.getMessage();
        }
        return se.tink.protobuf.custom.ComplexValue.getDefaultInstance();
      }
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    public Builder setComplexValue(se.tink.protobuf.custom.ComplexValue value) {
      if (complexValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        complexValueBuilder_.setMessage(value);
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    public Builder setComplexValue(
        se.tink.protobuf.custom.ComplexValue.Builder builderForValue) {
      if (complexValueBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        complexValueBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    public Builder mergeComplexValue(se.tink.protobuf.custom.ComplexValue value) {
      if (complexValueBuilder_ == null) {
        if (kindCase_ == 2 &&
            kind_ != se.tink.protobuf.custom.ComplexValue.getDefaultInstance()) {
          kind_ = se.tink.protobuf.custom.ComplexValue.newBuilder((se.tink.protobuf.custom.ComplexValue) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 2) {
          complexValueBuilder_.mergeFrom(value);
        } else {
          complexValueBuilder_.setMessage(value);
        }
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    public Builder clearComplexValue() {
      if (complexValueBuilder_ == null) {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
        }
        complexValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    public se.tink.protobuf.custom.ComplexValue.Builder getComplexValueBuilder() {
      return getComplexValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    @java.lang.Override
    public se.tink.protobuf.custom.ComplexValueOrBuilder getComplexValueOrBuilder() {
      if ((kindCase_ == 2) && (complexValueBuilder_ != null)) {
        return complexValueBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 2) {
          return (se.tink.protobuf.custom.ComplexValue) kind_;
        }
        return se.tink.protobuf.custom.ComplexValue.getDefaultInstance();
      }
    }
    /**
     * <code>.se.tink.ComplexValue complexValue = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        se.tink.protobuf.custom.ComplexValue, se.tink.protobuf.custom.ComplexValue.Builder, se.tink.protobuf.custom.ComplexValueOrBuilder> 
        getComplexValueFieldBuilder() {
      if (complexValueBuilder_ == null) {
        if (!(kindCase_ == 2)) {
          kind_ = se.tink.protobuf.custom.ComplexValue.getDefaultInstance();
        }
        complexValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            se.tink.protobuf.custom.ComplexValue, se.tink.protobuf.custom.ComplexValue.Builder, se.tink.protobuf.custom.ComplexValueOrBuilder>(
                (se.tink.protobuf.custom.ComplexValue) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 2;
      onChanged();;
      return complexValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:se.tink.NullableComplexValue)
  }

  // @@protoc_insertion_point(class_scope:se.tink.NullableComplexValue)
  private static final se.tink.protobuf.custom.NullableComplexValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new se.tink.protobuf.custom.NullableComplexValue();
  }

  public static se.tink.protobuf.custom.NullableComplexValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NullableComplexValue>
      PARSER = new com.google.protobuf.AbstractParser<NullableComplexValue>() {
    @java.lang.Override
    public NullableComplexValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NullableComplexValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NullableComplexValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public se.tink.protobuf.custom.NullableComplexValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

